version: '3.7'
services:
    postgres:
        env_file: [./app/.env, .env]
        image: postgres:14
        restart: always
        volumes:
            - ./data/pgsql_data:/data
            - ./data/pgsql_backup:/backup
        environment:
            PGDATA: "/data"
    phpfpm:
        build:
            context: .
            dockerfile: ./etc/docker/php-fpm-dev/Dockerfile
        depends_on: [postgres]
        env_file: [./app/.env, .env]
        user: "${UID}:${GID}"
        working_dir: /var/www/html
        volumes:
            - ./app:/var/www/html
            - ./etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    nginx:
        depends_on: [phpfpm]
        env_file: [./app/.env, .env]
        image: nginx:1.21
        ports: ["${HTTP_PORT:-8080}:80"]
        volumes:
            - ./app/public:/usr/share/nginx/html
            - ./data/logs/nginx:/var/log/nginx
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
